//
// Created by pbachmann on 2/11/16.
//

#ifndef HTWK_2016_OBSTACLEGRID_H
#define HTWK_2016_OBSTACLEGRID_H

#define ULTRASONIC_FRONT_LEFT_POS_X -15
#define ULTRASONIC_FRONT_LEFT_POS_Y 0

#define ULTRASONIC_FRONT_CENTER_LEFT_POS_X -5
#define ULTRASONIC_FRONT_CENTER_LEFT_POS_Y 0

#define ULTRASONIC_FRONT_CENTER_POS_X 0
#define ULTRASONIC_FRONT_CENTER_POS_Y 0

#define ULTRASONIC_FRONT_CENTER_RIGHT_POS_X 5
#define ULTRASONIC_FRONT_CENTER_RIGHT_POS_Y 0

#define ULTRASONIC_FRONT_RIGHT_POS_X 15
#define ULTRASONIC_FRONT_RIGHT_POS_Y 0

#define ULTRASONIC_SIDE_RIGHT_POS_X 15
#define ULTRASONIC_SIDE_RIGHT_POS_Y 40

#define ULTRASONIC_SIDE_LEFT_POS_X -15
#define ULTRASONIC_SIDE_LEFT_POS_Y 40

#define ULTRASONIC_REAR_LEFT_POS_X -15
#define ULTRASONIC_REAR_LEFT_POS_Y 60

#define ULTRASONIC_REAR_CENTER_POS_X 0
#define ULTRASONIC_REAR_CENTER_POS_Y 60

#define ULTRASONIC_REAR_RIGHT_POS_X 15
#define ULTRASONIC_REAR_RIGHT_POS_Y 60

#endif //HTWK_2016_OBSTACLEGRID_H
